name: biobb_md
channels:
  - conda-forge
  - bioconda
  - salilab
dependencies:
  - python==3.12
  - pip
  - biobb_common>=5.2.2
  - biobb_structure_utils>=5.2.1
  - biobb_model>=5.2.1
  - biobb_amber>=5.2.1
  - biobb_chemistry>=5.2.1
  - biobb_io>=5.2.3
  - biobb_pdb_tools>=5.2.1
  - propka==3.5.1
  - modeller>=10.8
  - mdanalysis
  - biopython
  - pip:
    - biobb_gromacs @ git+https://github.com/NBDsoftware/biobb_gromacs
    - biobb_analysis @ git+https://github.com/NBDsoftware/biobb_analysis
    - .                          # install biobb_md_workflows itself
